# Generated by Django 5.2 on 2025-04-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0006_remove_consultancyfirm_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancyfirm",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
