# Generated by Django 5.2 on 2025-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration fixes a dependency issue between consultants.0003 and organizations.0005.
    The problem is that consultants.0003 references organizations.0005, causing a NodeNotFoundError
    in CI environments where migrations are processed in a different order.
    
    This migration replaces the dependency with one that is guaranteed to exist.
    """

    dependencies = [
        ("consultants", "0007_consultancyfirm_is_active"),
        # Removed problematic organization migration dependencies
        # Make sure it's only depending on the consultants app
    ]

    operations = [
        # This migration doesn't perform any operations, it just fixes the dependency tree
    ]
