# Generated by Django 5.2 on 2025-04-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0009_ensure_dependencies_compatibility"),
        ("consultants", "0010_fix_dependencies_for_consultant_document"),
    ]

    operations = []
