# Generated by Django 5.2 on 2025-04-09 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_audit_certbody_audit_organization_and_more"),
        ("consultants", "0012_reset_migrations"),
        ("organizations", "0010_merge_20250410_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultantdocument",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_documents",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="consultantdocument",
            name="submitted_to_audit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_consultant_documents",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="consultantengagement",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_engagements",
                to="organizations.organization",
            ),
        ),
    ]
