# Generated by Django 5.2 on 2025-04-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0005_merge_20250408_0423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("certification_issued", "Certification Issued"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
    ]
