# Generated by Django 5.2 on 2025-04-09 23:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def skip_if_column_exists(apps, schema_editor, table, column):
    """Check if column exists in table and skip if it does"""
    db_alias = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()
    
    # SQLite specific check for column existence
    cursor.execute(
        "SELECT COUNT(*) FROM pragma_table_info(?) WHERE name = ?",
        [table, column]
    )
    if cursor.fetchone()[0] > 0:
        # Column already exists, return True to skip
        return True
    return False


class Migration(migrations.Migration):

    dependencies = [
        ("certification_bodies", "0003_certbodyuser_contact_phone"),
        ("organizations", "0010_merge_20250410_fix"),
        ("audits", "0006_change_audit_status_choices"),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_audit', 'certbody_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="audit",
            name="certbody",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="certification_bodies.certbody",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_audit', 'organization_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="audit",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="organizations.organization",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_auditorassignment', 'auditor_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="auditorassignment",
            name="auditor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="certification_bodies.auditor",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_auditresult', 'decided_by_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="auditresult",
            name="decided_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_decisions",
                to="certification_bodies.certbodyuser",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_auditteam', 'lead_auditor_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="auditteam",
            name="lead_auditor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_audits",
                to="certification_bodies.auditor",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_documentsubmission', 'consultant_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared_documents",
                to="consultants.consultant",
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None if skip_if_column_exists(
                apps, schema_editor, 'audits_documentsubmission', 'submitted_by_id') else None,
            reverse_code=lambda apps, schema_editor: None,
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                    ("certification_issued", "Certification Issued"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
