# Generated by Django 5.2 on 2025-04-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = []
