# Generated by Django 5.2 on 2025-04-07 22:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0002_remove_consultancyfirm_created_at_and_more"),
        # Remove dependency on organizations.0001_initial
        # Instead, depend on these migrations which should exist in all environments
        ("organizations", "0002_certification"),
        ("organizations", "0003_remove_certification_is_active_and_more"),
        ("organizations", "0004_organization_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancyfirm",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consultant",
            name="firm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultants",
                to="consultants.consultancyfirm",
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="is_independent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ConsultantEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Based"),
                            ("long_term", "Long Term Support"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to="consultants.consultant",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_engagements",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
