# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0003_consultancyfirm_created_at_consultant_firm_and_more"),
        ("consultants", "0004_add_consultant_document"),
    ]

    operations = []
