# Generated by Django 5.2 on 2025-04-08 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0005_merge_20250408_0423"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultancyfirm",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="consultantengagement",
            name="description",
        ),
        migrations.RemoveField(
            model_name="consultantengagement",
            name="engagement_type",
        ),
        migrations.RemoveField(
            model_name="consultantengagement",
            name="is_active",
        ),
        migrations.AddField(
            model_name="consultancyfirm",
            name="specialties",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consultancyfirm",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="consultancyfirm",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="consultant",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consultant",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consultant",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="consultant",
            name="specialties",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consultant",
            name="standards",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="consultant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="consultantengagement",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="consultantengagement",
            name="standards",
            field=models.CharField(default="ISO 9001", max_length=255),
        ),
        migrations.AddField(
            model_name="consultantengagement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultancyfirm",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="consultantengagement",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
