# Generated by Django 5.2 on 2025-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration fixes a dependency issue between consultants.0003 and organizations.0005.
    The problem is that consultants.0003 references organizations.0005, causing a NodeNotFoundError
    in CI environments where migrations are processed in a different order.
    
    This migration replaces the dependency with one that is guaranteed to exist.
    """

    dependencies = [
        ("consultants", "0007_consultancyfirm_is_active"),
        # Make sure to depend on all possible organization migrations to ensure they run first
        ("organizations", "0001_initial"),
        ("organizations", "0002_certification"),
        ("organizations", "0003_remove_certification_is_active_and_more"),
        ("organizations", "0004_organization_is_active"),
        ("organizations", "0005_certification_standard_organization_address_and_more"),
        ("organizations", "0006_alter_organization_created_at"),
        # Add all potential dependencies to make sure this migration runs after all organization migrations
    ]

    operations = [
        # This migration doesn't perform any operations, it just fixes the dependency tree
    ]
