# Generated by Django 5.2 on 2025-04-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a secondary migration that ensures all dependencies are properly resolved.
    It's needed to prevent issues with CI/CD environments where migrations might be applied
    in a different order than in development.
    """

    dependencies = [
        ("consultants", "0008_fix_migration_dependency"),
        # Depend on migrations we know exist in CI rather than one that might not exist yet
        ("organizations", "0008_merge_20250408_0423"),  # Use an earlier merge migration that should exist
        ("organizations", "0009_remove_organizationuser_joined_date_and_more"),  # Add another known migration
    ]

    operations = [
        # No database changes, just fixing dependencies
    ]
