# Generated by Django 5.2 on 2025-04-09 09:10

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a secondary migration that ensures all dependencies are properly resolved.
    It's needed to prevent issues with CI/CD environments where migrations might be applied
    in a different order than in development.
    """

    dependencies = [
        ("consultants", "0008_fix_migration_dependency"),
        # Removed problematic dependencies to other apps
    ]

    operations = [
        # No database changes, just fixing dependencies
    ]
