# Generated by Django 5.2 on 2025-04-09 09:26

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration fixes the dependency issue for consultants.0004_add_consultant_document migration.
    The problem is that it depends on organizations.0007_add_certification_scope_and_audit_link,
    which doesn't exist in the CI environment.
    """

    dependencies = [
        ("consultants", "0003_consultancyfirm_created_at_consultant_firm_and_more"),
        ("organizations", "0001_initial"),  # Ensure minimal dependency
        ("organizations", "0002_certification"),
        ("organizations", "0003_remove_certification_is_active_and_more"),
        ("organizations", "0004_organization_is_active"),
        ("organizations", "0005_certification_standard_organization_address_and_more"),
        ("organizations", "0006_alter_organization_created_at"),
    ]

    operations = [
        # This migration only exists to fix the dependency tree,
        # it doesn't perform any actual database changes
    ]
