# Generated by Django 5.1.8 on 2025-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_bodies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certbody",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="certbody",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="certbody",
            name="accreditation_id",
            field=models.CharField(max_length=100),
        ),
    ]
