# Generated by fix_ci_migrations.py
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix CI dependency chain."""

    dependencies = [("certification_bodies", "0001_initial")]

    operations = []
