# Generated by fix_ci_migrations.py
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration created to fix CI dependency chain."""

    dependencies = [
        ("certification_bodies", "0001_initial")
    ]

    operations = []
