# Generated by fix_ci_migrations.py
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix CI dependency chain."""

    dependencies = [("certification_bodies", "0002_alter_certbody_options")]

    operations = [
        migrations.AddField(
            model_name="certbodyuser",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
