# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_bodies",
            "0003_certbody_contact_email_certbody_is_active_auditor_and_more",
        ),
        ("certification_bodies", "0004_add_standard_qualification"),
    ]

    operations = []
