# Generated by Django 5.2 on 2025-04-12 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Removed dependency on certification_bodies to resolve NodeNotFoundError
        ("consultants", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("pre_assessment", "Pre-Assessment"),
                            ("stage1", "Stage 1"),
                            ("stage2", "Stage 2"),
                            ("surveillance", "Surveillance"),
                            ("recertification", "Re-certification"),
                        ],
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("certification_issued", "Certification Issued"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        default="ISO 9001:2015",
                        help_text="The standard being audited against",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "certbody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="certification_bodies.certbody",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve Certification"),
                            ("conditional", "Conditional Approval"),
                            ("reject", "Reject Certification"),
                            ("followup", "Followup Audit Required"),
                        ],
                        max_length=20,
                    ),
                ),
                ("decision_date", models.DateField(default=django.utils.timezone.now)),
                ("comments", models.TextField(blank=True)),
                ("nonconformances_closed", models.BooleanField(default=False)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("issue", "Issue Certificate"),
                            ("withhold", "Withhold Certificate"),
                            ("withdraw", "Withdraw Certificate"),
                            ("followup", "Followup Required"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="audits.audit",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_decisions",
                        to="certification_bodies.certbodyuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_team",
                        to="audits.audit",
                    ),
                ),
                (
                    "lead_auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lead_audits",
                        to="certification_bodies.auditor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead Auditor"),
                            ("technical", "Technical Expert"),
                            ("trainee", "Trainee Auditor"),
                            ("observer", "Observer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("unassigned_date", models.DateField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="certification_bodies.auditor",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="audits.auditteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy Document"),
                            ("procedure", "Procedure"),
                            ("record", "Record"),
                            ("evidence", "Compliance Evidence"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="audit_documents/")),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="audits.audit",
                    ),
                ),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_documents",
                        to="consultants.consultant",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("observation", "Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_raised", models.DateField(auto_now_add=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("requires_evidence", models.BooleanField(default=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonconformances",
                        to="audits.audit",
                    ),
                ),
            ],
        ),
    ]
