# Generated by Django 5.2 on 2025-04-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audits", "0001_initial"),
        ("certification_bodies", "0001_initial"),
        ("consultants", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="auditorassignment",
            name="auditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="certification_bodies.auditor",
            ),
        ),
        migrations.AddField(
            model_name="auditresult",
            name="audit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="auditresult",
            name="decided_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_decisions",
                to="certification_bodies.certbodyuser",
            ),
        ),
        migrations.AddField(
            model_name="auditteam",
            name="audit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_team",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="auditteam",
            name="lead_auditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_audits",
                to="certification_bodies.auditor",
            ),
        ),
        migrations.AddField(
            model_name="auditorassignment",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="audits.auditteam",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared_documents",
                to="consultants.consultant",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nonconformances",
                to="audits.audit",
            ),
        ),
    ]
