# Generated by Django 5.2 on 2025-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
