# Generated by Django 5.2 on 2025-04-10 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_audit_scheduled_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditresult",
            old_name="notes",
            new_name="comments",
        ),
    ]
