# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_audit_notes_audit_standard_alter_audit_audit_type_and_more"),
        ("audits", "0004_add_document_submission_audit_result"),
    ]

    # We leave operations empty because both migrations are trying to modify the same fields
    # and we've already applied the changes from migration 0003
    operations = [
        # No operations needed - field status already exists from 0003 migration
    ]
