# Generated by Django 5.1.8 on 2025-04-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_remove_certification_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
