# Generated by Django 5.2 on 2025-04-07 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_certification_standard_organization_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
