# Generated by Django 5.2 on 2025-04-08 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "certification_bodies",
            "0006_remove_certbodyuser_joined_date_auditor_bio_and_more",
        ),
        ("organizations", "0008_merge_20250408_0423"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationuser",
            name="joined_date",
        ),
        migrations.AddField(
            model_name="organization",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="organizationuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="cert_body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_certifications",
                to="certification_bodies.certbody",
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="certificate_number",
            field=models.CharField(
                help_text="The unique certificate identifier",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="standard",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("viewer", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certification",
            unique_together={("organization", "standard", "cert_body", "issue_date")},
        ),
    ]
