# Generated by fix_ci_migrations.py
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix CI dependency chain."""

    dependencies = [
        ("organizations", "0007_add_certification_scope_and_audit_link"),
        ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
    ]

    operations = []
