# Generated by Django 5.2 on 2025-04-10 12:30

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is created to fix dependency issues between
    branches 0007_add_certification_scope_and_audit_link and 0009_remove_organizationuser_joined_date_and_more.
    """

    dependencies = [
        ("organizations", "0007_add_certification_scope_and_audit_link"),
        ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
    ]

    operations = [
        # No operations needed for this merge migration
    ]
