#!/usr/bin/env python
"""
Create Missing Migrations Script

This script directly creates the missing migration file that's causing issues in CI.
The file is organizations/migrations/0010_merge_20250409_0505.py which is referenced
by several other migrations but might be missing in the CI environment.

Usage:
    python create_missing_migrations.py
"""

import os
from pathlib import Path

def ensure_migration_exists():
    """Create the missing migration file if it doesn't exist."""
    base_path = Path(__file__).resolve().parent
    migration_path = base_path / "apps" / "organizations" / "migrations" / "0010_merge_20250409_0505.py"
    
    if migration_path.exists():
        print(f"Migration already exists: {migration_path}")
        return
    
    print(f"Creating migration file: {migration_path}")
    
    # Ensure directory exists
    migration_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Create a simple empty migration with the necessary dependencies
    with open(migration_path, 'w') as f:
        f.write("""# Generated by create_missing_migrations.py
from django.db import migrations


class Migration(migrations.Migration):
    \"\"\"Migration created to fix dependency chain for CI.\"\"\"

    dependencies = [
        ("organizations", "0007_add_certification_scope_and_audit_link"),
        ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
    ]

    operations = [
        # No operations, this is just to fix dependency chains
    ]
""")
    print("Migration file created successfully")

if __name__ == "__main__":
    ensure_migration_exists()