#!/usr/bin/env python
"""
Fix All Migrations Script

This script comprehensively fixes all migration dependency issues by:
1. Creating any missing migration files
2. Ensuring all migration paths are consistent
3. Testing that the migration graph can be built successfully

Run this before running migrations or tests to ensure a consistent environment.

Usage:
    python fix_all_migrations.py
"""

import importlib
import os
import sys
from pathlib import Path

import django
from django.conf import settings

# Configure Django settings
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "scopewatch.settings")
if not settings.configured:
    django.setup()


def create_migration_file(app_name, migration_name, dependencies, operations=None):
    """Create a migration file with the specified dependencies."""
    base_path = Path(__file__).resolve().parent
    migration_path = base_path / "apps" / app_name / "migrations" / migration_name

    # Ensure parent directory exists
    migration_path.parent.mkdir(parents=True, exist_ok=True)

    # Format dependencies for the migration file
    deps_str = ",\n        ".join(
        [f'("{app}", "{name}")' for app, name in dependencies]
    )

    # Default operations if none provided
    if operations is None:
        operations_str = "    operations = []"
    else:
        operations_str = (
            "    operations = [\n        " + ",\n        ".join(operations) + "\n    ]"
        )

    # Create the migration file
    with open(migration_path, "w") as f:
        f.write(
            f'''# Generated by fix_all_migrations.py
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration created to fix dependency issues in CI environment."""

    dependencies = [
        {deps_str}
    ]

{operations_str}
'''
        )
    print(f"Created migration file: {migration_path}")
    return True


def create_required_migrations():
    """Create all necessary migration files to fix dependency issues."""

    # Dictionary of missing migrations to create
    missing_migrations = [
        # Organization migrations
        {
            "app": "organizations",
            "name": "0010_merge_20250409_0505.py",
            "dependencies": [
                ("organizations", "0007_add_certification_scope_and_audit_link"),
                ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
            ],
            "operations": [],
        },
        # Audit migrations
        {
            "app": "audits",
            "name": "0005_alter_nonconformance_status.py",
            "dependencies": [("audits", "0004_add_document_submission_audit_result")],
            "operations": [
                """migrations.AlterField(
                    model_name="nonconformance",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("in_review", "In Review"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                )"""
            ],
        },
        {
            "app": "audits",
            "name": "0006_change_audit_status_choices.py",
            "dependencies": [("audits", "0005_alter_nonconformance_status")],
            "operations": [
                """migrations.AlterField(
                    model_name="audit",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("certification_issued", "Certification Issued"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                )"""
            ],
        },
        # Certification Bodies migrations
        {
            "app": "certification_bodies",
            "name": "0003_certbodyuser_contact_phone.py",
            "dependencies": [("certification_bodies", "0002_alter_certbody_options")],
            "operations": [
                """migrations.AddField(
                    model_name="certbodyuser",
                    name="contact_phone",
                    field=models.CharField(blank=True, max_length=20, null=True),
                )"""
            ],
        },
    ]

    # Create all missing migrations
    for migration in missing_migrations:
        create_migration_file(
            migration["app"],
            migration["name"],
            migration["dependencies"],
            migration.get("operations"),
        )


def validate_migrations():
    """Validate that all migrations can be loaded correctly."""
    try:
        # Import the MigrationLoader to test if the migration graph can be built
        from django.db import connections
        from django.db.migrations.loader import MigrationLoader

        # Get the default database connection
        connection = connections["default"]

        # Try to build the migration graph
        loader = MigrationLoader(connection)
        print("Successfully built migration graph!")

        # Count migrations
        migration_count = sum(
            1 for node in loader.graph.nodes if node[0] != "__setting__"
        )
        print(f"Found {migration_count} migrations in the graph")

        # Check for any missing dependencies (DummyNodes)
        dummy_nodes = [
            node
            for node in loader.graph.node_map.values()
            if hasattr(loader.graph, "DummyNode")
            and isinstance(node, loader.graph.DummyNode)
        ]

        if dummy_nodes:
            print("\nWARNING: There are still missing migrations:")
            for node in dummy_nodes:
                print(f"  - Missing: {node.key}")
            return False

        return True
    except Exception as e:
        print(f"\nERROR: Failed to validate migrations: {str(e)}")
        return False


if __name__ == "__main__":
    print("Starting comprehensive migration fixes...")

    # Create all required migrations
    create_required_migrations()

    # Validate that the migrations can now be loaded correctly
    if validate_migrations():
        print("\nAll migration dependencies have been fixed successfully!")
    else:
        print("\nSome migration issues remain. You may need to add more migrations.")

    print("\nMigration fix completed.")
    sys.exit(0)
