#!/usr/bin/env python
"""
Migration Chain Fixer

This script automatically fixes Django migration dependency issues by:
1. Creating any missing migrations
2. Updating dependencies in existing migrations
3. Ensuring the migration graph is consistent

Run this script before migrations in CI to ensure all migration dependencies can be resolved.

Usage:
    python fix_migration_chain.py
"""

import json
import os
import re
import sys
from pathlib import Path


def create_migration_file(app_name, migration_name, dependencies):
    """Create a migration file with the specified dependencies."""
    base_path = Path(__file__).resolve().parent
    migration_path = base_path / "apps" / app_name / "migrations" / migration_name

    if migration_path.exists():
        print(f"Migration already exists: {migration_path}")
        return

    # Ensure parent directories exist
    migration_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Creating migration file: {migration_path}")

    # Format dependencies for the migration file
    deps_str = ",\n        ".join(
        [f'("{app}", "{name}")' for app, name in dependencies]
    )

    # Create a simple empty migration with the necessary dependencies
    with open(migration_path, "w") as f:
        f.write(
            f'''# Generated by fix_migration_chain.py
from django.db import migrations


class Migration(migrations.Migration):
    """Migration created to fix dependency chain for CI."""

    dependencies = [
        {deps_str}
    ]

    operations = [
        # No operations, this is just to fix dependency chains
    ]
'''
        )
    print(f"Created migration file: {migration_path}")
    return migration_path


def fix_migration_dependencies(file_path, old_dependency, new_dependency):
    """Replace a dependency in a migration file."""
    if not file_path.exists():
        print(f"Warning: Migration file not found: {file_path}")
        return

    print(f"Checking dependencies in {file_path}")

    # Read the file content
    with open(file_path, "r") as file:
        content = file.read()

    # Check if it contains the dependency we want to replace
    old_dep_str = f'("{old_dependency[0]}", "{old_dependency[1]}")'
    new_dep_str = f'("{new_dependency[0]}", "{new_dependency[1]}")'

    if old_dep_str in content:
        # Replace the dependency
        modified_content = content.replace(old_dep_str, new_dep_str)

        # Write back the modified file
        with open(file_path, "w") as file:
            file.write(modified_content)
        print(f"  Fixed dependency in {file_path.name}: {old_dep_str} -> {new_dep_str}")
        return True

    return False


def ensure_migration_chain():
    """Ensure all required migrations exist and have correct dependencies."""
    base_path = Path(__file__).resolve().parent

    # Fix known missing migrations
    missing_migrations = [
        {
            "app": "organizations",
            "name": "0010_merge_20250410_1230.py",
            "dependencies": [
                ("organizations", "0007_add_certification_scope_and_audit_link"),
                ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
            ],
        },
        {
            "app": "audits",
            "name": "0006_change_audit_status_choices.py",
            "dependencies": [("audits", "0005_alter_nonconformance_status")],
        },
    ]

    # Create any missing migrations
    for migration in missing_migrations:
        create_migration_file(
            migration["app"], migration["name"], migration["dependencies"]
        )

    # Fix dependencies in existing migrations
    dependency_fixes = [
        {
            "app": "consultants",
            "migration": "0013_consultantdocument_organization_and_more.py",
            "old_dependency": ("organizations", "0010_merge_20250409_0505"),
            "new_dependency": ("organizations", "0010_merge_20250410_1230"),
        },
        {
            "app": "public",
            "migration": "0002_certificationverification_certificate.py",
            "old_dependency": ("organizations", "0010_merge_20250409_0505"),
            "new_dependency": ("organizations", "0010_merge_20250410_1230"),
        },
        {
            "app": "audits",
            "migration": "0007_audit_certbody_audit_organization_and_more.py",
            "old_dependency": ("organizations", "0010_merge_20250409_0505"),
            "new_dependency": ("organizations", "0010_merge_20250410_1230"),
        },
    ]

    for fix in dependency_fixes:
        fix_migration_dependencies(
            base_path / "apps" / fix["app"] / "migrations" / fix["migration"],
            fix["old_dependency"],
            fix["new_dependency"],
        )

    print("Migration chain fixed successfully!")


if __name__ == "__main__":
    ensure_migration_chain()
