#!/usr/bin/env python
"""
Direct Migration Fix for Inconsistent History

This script specifically fixes the inconsistent migration history error:
"Migration audits.0007_audit_certbody_audit_organization_and_more is applied before 
its dependency certification_bodies.0003_certbodyuser_contact_phone on database 'default'."

The script:
1. Creates the missing certification_bodies migration
2. Marks it as applied in the database
3. Resets the migration history to a consistent state

Usage:
    python fix_migration_now.py
"""

import os
import sys
import django
from django.db import connections
from pathlib import Path

# Set up Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'scopewatch.settings')
django.setup()

def create_missing_migration():
    """Create the missing certification_bodies migration"""
    base_path = Path(__file__).resolve().parent
    
    # Define the migration file path
    migration_dir = base_path / "apps" / "certification_bodies" / "migrations"
    migration_path = migration_dir / "0003_certbodyuser_contact_phone.py"
    
    if migration_path.exists():
        print(f"Migration {migration_path} already exists")
        return True
    
    print(f"Creating migration: {migration_path}")
    
    # Make sure directory exists
    migration_dir.mkdir(parents=True, exist_ok=True)
    
    # Create the migration file with minimal content
    migration_content = '''# Generated by fix_migration_now.py
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix dependency issue with audits.0007."""

    dependencies = [
        ('certification_bodies', '0002_alter_certbody_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certbodyuser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
'''
    
    with open(migration_path, 'w') as f:
        f.write(migration_content)
    
    print(f"✅ Created migration: {migration_path}")
    return True

def fix_migration_history():
    """Fix the migration history in the database"""
    # Get database connection
    connection = connections['default']
    
    print("Fixing migration history in database...")
    
    # Check if the problematic migration is already in the database
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT * FROM django_migrations WHERE app = %s AND name = %s",
            ["certification_bodies", "0003_certbodyuser_contact_phone"]
        )
        exists = cursor.fetchone() is not None
        
        if not exists:
            # Insert the migration record with a timestamp earlier than audits.0007
            cursor.execute(
                """
                SELECT applied FROM django_migrations 
                WHERE app = %s AND name = %s
                """,
                ["audits", "0007_audit_certbody_audit_organization_and_more"]
            )
            
            audit_timestamp = cursor.fetchone()
            if not audit_timestamp:
                # If audits.0007 is not in the database, just use current time
                cursor.execute(
                    """
                    INSERT INTO django_migrations (app, name, applied)
                    VALUES (%s, %s, datetime('now', '-1 hour'))
                    """,
                    ["certification_bodies", "0003_certbodyuser_contact_phone"]
                )
                print("✅ Added missing migration record with timestamp 1 hour ago")
            else:
                # Make sure our new record has earlier timestamp
                cursor.execute(
                    """
                    INSERT INTO django_migrations (app, name, applied)
                    VALUES (%s, %s, datetime(%s, '-1 minute'))
                    """,
                    ["certification_bodies", "0003_certbodyuser_contact_phone", audit_timestamp[0]]
                )
                print("✅ Added missing migration with timestamp before audits.0007")
        else:
            print("Migration record already exists in the database")
    
    print("✅ Migration history fixed")
    return True

def verify_fix():
    """Verify that the fix worked by running migrations"""
    import subprocess
    
    print("\nVerifying fix by running migrations...")
    try:
        subprocess.run(["python", "manage.py", "migrate"], check=True)
        print("✅ Migrations applied successfully! The fix worked.")
        return True
    except subprocess.CalledProcessError:
        print("❌ Migration still failing. Let's try a more aggressive fix...")
        
        # Reset the entire migration history for these apps
        connection = connections['default']
        with connection.cursor() as cursor:
            # Delete the problematic migrations
            cursor.execute(
                "DELETE FROM django_migrations WHERE app IN (%s, %s)",
                ["audits", "certification_bodies"]
            )
            print("Deleted migration records for audits and certification_bodies")
            
            # Fake apply these migrations
            try:
                subprocess.run(["python", "manage.py", "migrate", "certification_bodies", "--fake"], check=True)
                subprocess.run(["python", "manage.py", "migrate", "audits", "--fake"], check=True)
                subprocess.run(["python", "manage.py", "migrate"], check=True)
                print("✅ Second attempt succeeded! The fix worked.")
                return True
            except subprocess.CalledProcessError as e:
                print(f"❌ Migration still failing after second attempt: {e}")
                return False

def main():
    """Main function to fix the migration issue"""
    print("=" * 60)
    print("🔧 Direct Migration Fix for Inconsistent History")
    print("=" * 60)
    
    # Create the missing migration file
    if not create_missing_migration():
        print("❌ Failed to create missing migration")
        return 1
    
    # Fix the migration history in the database
    if not fix_migration_history():
        print("❌ Failed to fix migration history")
        return 1
    
    # Verify the fix
    if not verify_fix():
        print("\n❌ Fix verification failed")
        print("Try running: python manage.py migrate --fake certification_bodies")
        print("Then:        python manage.py migrate --fake audits")
        print("Finally:     python manage.py migrate")
        return 1
    
    print("\n✅ Migration issue fixed successfully!")
    return 0

if __name__ == "__main__":
    sys.exit(main())