#!/usr/bin/env python
"""
Fix Django Migrations Script

This script creates all necessary migration files to fix dependency issues:
1. Creates missing organization migration files
2. Creates missing audit migration files
3. Ensures all migration dependencies are satisfied

Usage:
    python fix_migrations.py
"""

import os
import re
import sys
from pathlib import Path


def create_migration_file(app_name, migration_name, dependencies, operations=None):
    """Create a migration file with the specified dependencies."""
    base_path = Path(__file__).resolve().parent
    migration_path = base_path / "apps" / app_name / "migrations" / migration_name
    
    # Ensure parent directory exists
    migration_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Delete the file if it exists (to ensure clean creation)
    if migration_path.exists():
        migration_path.unlink()
        print(f"Removed existing file: {migration_path}")
    
    # Format dependencies for the migration file
    deps_str = ",\n        ".join([f'("{app}", "{name}")' for app, name in dependencies])
    
    # Default operations if none provided
    if operations is None:
        operations_str = "    operations = []"
    else:
        operations_str = "    operations = [\n        " + ",\n        ".join(operations) + "\n    ]"
    
    # Create the migration file
    with open(migration_path, 'w') as f:
        f.write(f'''# Generated by fix_migrations.py
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix dependency issues in CI environment."""

    dependencies = [
        {deps_str}
    ]

{operations_str}
''')
    print(f"Created migration file: {migration_path}")
    return True


def fix_all_migrations():
    """Create all necessary migration files to fix dependency issues."""
    
    # Create the organization merge migration
    create_migration_file(
        "organizations",
        "0010_merge_20250409_0505.py",
        [
            ("organizations", "0007_add_certification_scope_and_audit_link"),
            ("organizations", "0009_remove_organizationuser_joined_date_and_more")
        ]
    )
    
    # Create the missing audits migrations
    create_migration_file(
        "audits",
        "0005_alter_nonconformance_status.py",
        [
            ("audits", "0004_add_document_submission_audit_result")
        ],
        [
            '''migrations.AlterField(
                model_name="nonconformance",
                name="status",
                field=models.CharField(
                    choices=[
                        ("open", "Open"),
                        ("closed", "Closed"),
                        ("in_review", "In Review"),
                    ],
                    default="open",
                    max_length=20,
                ),
            )'''
        ]
    )
    
    # Now create the dependent migration
    create_migration_file(
        "audits",
        "0006_change_audit_status_choices.py",
        [
            ("audits", "0005_alter_nonconformance_status")
        ],
        [
            '''migrations.AlterField(
                model_name="audit",
                name="status",
                field=models.CharField(
                    choices=[
                        ("scheduled", "Scheduled"),
                        ("in_progress", "In Progress"),
                        ("completed", "Completed"),
                        ("closed", "Closed"),
                        ("certification_issued", "Certification Issued"),
                    ],
                    default="scheduled",
                    max_length=50,
                ),
            )'''
        ]
    )


if __name__ == "__main__":
    print("Starting migration fixes...")
    fix_all_migrations()
    print("\nMigration fixes completed successfully!")
    print("All missing migration files have been created.")
    sys.exit(0)