#!/usr/bin/env python
"""
Migration Dependency Resolver

This script fixes migration dependencies before running tests.
It specifically addresses the issue where certain migrations reference
organizations.0010_merge_20250409_0505 which may not be properly
recognized in some environments.

Usage:
    python fix_migration_dependencies.py
"""

import fileinput
import os
import re
import sys
from pathlib import Path


def find_migration_files(app_name, migration_pattern):
    """Find migration files for a specific app that match a pattern."""
    base_path = Path(__file__).resolve().parent
    migration_dir = base_path / "apps" / app_name / "migrations"

    if not migration_dir.exists():
        print(f"Migration directory not found: {migration_dir}")
        return []

    pattern = re.compile(migration_pattern)
    return [f for f in migration_dir.glob("*.py") if pattern.search(f.name)]


def fix_dependency_references(file_path, old_dep, new_dep):
    """Replace dependency references in a migration file."""
    print(f"Fixing dependencies in {file_path}")
    with fileinput.FileInput(file_path, inplace=True) as file:
        for line in file:
            if old_dep in line:
                print(line.replace(old_dep, new_dep), end="")
            else:
                print(line, end="")


def ensure_migration_exists(app_name, migration_name, deps_to_use):
    """Ensure a specific migration exists, creating it if necessary."""
    base_path = Path(__file__).resolve().parent
    migration_path = base_path / "apps" / app_name / "migrations" / migration_name

    if migration_path.exists():
        print(f"Migration already exists: {migration_path}")
        return

    print(f"Creating migration file: {migration_path}")

    # Create a simple empty migration with the necessary dependencies
    with open(migration_path, "w") as f:
        f.write(
            f'''# Generated by fix_migration_dependencies.py
from django.db import migrations


class Migration(migrations.Migration):
    """Migration created to fix dependency issues in CI."""

    dependencies = [
        {deps_to_use}
    ]

    operations = [
        # No operations, this is just to fix dependency chains
    ]
'''
        )


def main():
    """Main function to fix migration dependencies."""
    print("Starting migration dependency resolver...")

    # Handle the organizations app migrations
    org_migration_files = find_migration_files(
        "organizations", r"0010_merge_20250409_0505\.py"
    )
    if not org_migration_files:
        # Create a replacement migration to satisfy dependencies
        ensure_migration_exists(
            "organizations",
            "0010_merge_20250409_0505.py",
            '("organizations", "0009_remove_organizationuser_joined_date_and_more"),\n'
            '        ("organizations", "0007_add_certification_scope_and_audit_link"),',
        )

    # Find all migration files that reference the problematic migration
    for app_name in ["consultants", "public", "audits"]:
        migration_files = find_migration_files(app_name, r"\.py$")
        for file_path in migration_files:
            with open(file_path, "r") as f:
                content = f.read()
                if '"organizations", "0010_merge_20250409_0505"' in content:
                    # Fix the dependency reference to use the previous migration instead
                    fix_dependency_references(
                        file_path,
                        '"organizations", "0010_merge_20250409_0505"',
                        '"organizations", "0009_remove_organizationuser_joined_date_and_more"',
                    )

    print("Migration dependency resolver completed successfully!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
