# Generated by Django 5.2 on 2025-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certification_bodies", "0002_initial"),
    ]

    operations = []
