# Generated by Django 5.2 on 2025-04-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_bodies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditor",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="auditor_qualifications",
                to="certification_bodies.standardqualification",
            ),
        ),
        migrations.AlterField(
            model_name="standardqualification",
            name="auditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standard_qualifications",
                to="certification_bodies.auditor",
            ),
        ),
    ]
