# Generated by Django 5.2 on 2025-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_merge_20250409_0505"),
        ("organizations", "0010_merge_20250410_fix"),
    ]

    operations = []
