# Generated by Django 5.2 on 2025-04-09 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_merge_20250409_0505"),
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationverification",
            name="certificate",
            field=models.ForeignKey(
                null=True,  # Changed from django.utils.timezone.now to null
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_records",
                to="organizations.certification",
            ),
        ),
    ]
