# Generated by Django 5.2 on 2025-04-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationverification",
            name="temporary_field",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
