# Generated by Django 5.2 on 2025-04-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_certificationverification_temporary_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificationverification",
            name="temporary_field",
        ),
    ]
