# Generated by Django 5.2 on 2025-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_remove_certificationverification_temporary_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificationverification",
            name="temporary_field",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
