# Generated by Django 5.1.8 on 2025-04-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audit",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="audit",
            name="updated_at",
        ),
    ]
