# Generated by Django 5.2 on 2025-04-07 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_remove_audit_created_at_remove_audit_updated_at"),
        # Removed cross-app dependency on certification_bodies
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="audit",
            name="standard",
            field=models.CharField(
                default="ISO 9001:2015",
                help_text="The standard being audited against",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("pre_assessment", "Pre-Assessment"),
                    ("stage1", "Stage 1"),
                    ("stage2", "Stage 2"),
                    ("surveillance", "Surveillance"),
                    ("recertification", "Re-certification"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("closed", "Closed"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AuditTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_team",
                        to="audits.audit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead Auditor"),
                            ("technical", "Technical Expert"),
                            ("trainee", "Trainee Auditor"),
                            ("observer", "Observer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_date", models.DateField(auto_now_add=True)),
                ("unassigned_date", models.DateField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="audits.auditteam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("observation", "Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date_raised", models.DateField(auto_now_add=True)),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("requires_evidence", models.BooleanField(default=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonconformances",
                        to="audits.audit",
                    ),
                ),
            ],
        ),
    ]
