# Generated by Django 5.2 on 2025-04-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_alter_audit_status"),
        ("audits", "0007_audit_certbody_audit_organization_and_more"),
    ]

    operations = []
