# Generated by Django 5.2 on 2025-04-08 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certification_bodies", "0005_merge_20250408_0423"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certbodyuser",
            name="joined_date",
        ),
        migrations.AddField(
            model_name="auditor",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditor",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="auditor",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="auditor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="certbody",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="certbody_logos/"),
        ),
        migrations.AddField(
            model_name="certbody",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="certbodyuser",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="certbodyuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="cert_bodies",
            field=models.ManyToManyField(
                related_name="auditors", to="certification_bodies.certbody"
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="certbody",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="certbody",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="certbodyuser",
            name="cert_body",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="certification_bodies.certbody",
            ),
        ),
        migrations.AlterField(
            model_name="certbodyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("manager", "Manager"),
                    ("certifier", "Certification Manager"),
                    ("staff", "Staff Member"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="certbodyuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
