# Generated by Django 5.2 on 2025-04-09 09:26

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration fixes the dependency issue for consultants.0004_add_consultant_document migration.
    The problem is that it depends on organizations.0007_add_certification_scope_and_audit_link,
    which doesn't exist in the CI environment.
    """

    dependencies = [
        ("consultants", "0009_ensure_dependencies_compatibility"),
        # Removed cross-app dependencies to organizations
    ]

    operations = [
        # This migration only exists to fix the dependency tree,
        # it doesn't perform any actual database changes
    ]
