# Generated by Django 5.1.8 on 2025-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_certification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certification",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="certification",
            name="standard",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
    ]
