# Generated by Django 5.2 on 2025-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_temporary_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="temporary_field_2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
