# Generated by Django 5.2 on 2025-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organization_created_at"),
        ("organizations", "0007_add_certification_scope_and_audit_link"),
    ]

    operations = []
