# Generated by fix_migrations.py
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration created to fix dependency issues in CI environment."""

    dependencies = [
        ("organizations", "0007_add_certification_scope_and_audit_link"),
        ("organizations", "0009_remove_organizationuser_joined_date_and_more")
    ]

    operations = []
