# Generated by Django 5.2 on 2025-04-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_add_certification_scope_and_audit_link"),
        ("organizations", "0009_remove_organizationuser_joined_date_and_more"),
    ]

    operations = []
